language: node_js

stages:
- name: deploy
  if: branch = master

jobs:
  include:
    - stage: npm release
      node_js: "8"
      install: skip
      script: skip
      if: NOT type = pull_request
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: deploy-npm-release

